obj-m += lcec.o

lcec-driver-objs := \
    lcec_devicelist.o \
    lcec_ethercat.o \
    lcec_pins.o \
    lcec_class_enc.o \
    lcec_class_ax5.o \
    lcec_generic.o \
    lcec_ax5100.o \
    lcec_ax5200.o \
    lcec_el1xxx.o \
    lcec_el1252.o \
    lcec_el1859.o \
    lcec_el2521.o \
    lcec_el2xxx.o \
    lcec_el2202.o \
    lcec_el30x4.o \
    lcec_el31x2.o \
    lcec_el31x4.o \
    lcec_el3202.o \
    lcec_el3255.o \
    lcec_el3403.o \
    lcec_el40x1.o \
    lcec_el40x2.o \
    lcec_el40x8.o \
    lcec_el41x2.o \
    lcec_el41x4.o \
    lcec_el5002.o \
    lcec_el5032.o \
    lcec_el5101.o \
    lcec_el5151.o \
    lcec_el5152.o \
    lcec_el6090.o \
    lcec_el6900.o \
    lcec_el1918_logic.o \
    lcec_el1904.o \
    lcec_el2904.o \
    lcec_el7041.o \
    lcec_ax5805.o \
    lcec_el70x1.o \
    lcec_el7211.o \
    lcec_el7342.o \
    lcec_el7411.o \
    lcec_el95xx.o \
    lcec_em37xx.o \
    lcec_em7004.o \
    lcec_ep23xx.o \
    lcec_ep2316.o \
    lcec_stmds5k.o \
    lcec_deasda.o \
    lcec_dems300.o \
    lcec_omrg5.o \
    lcec_ph3lm2rm.o

lcec-objs := \
    lcec_main.o \
    $(lcec-driver-objs)

