.PHONY: clean

clean:
	rm -f *.so *.ko *.o *.a devices/*.o devices/*.a
	rm -f *.d devices/*.d
	rm -f *.sym *.tmp *.ver
	rm -f *.mod.c .*.cmd
	rm -f modules.order Module.symvers
	rm -rf .tmp_versions
	rm -f lcec_conf


